version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - app-network
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data

  fastapi-app-org-service:
    build: .
    container_name: fastapi_app_org_service
    ports:
      - "8000:8000"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
    networks:
      - app-network
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs

  set-data-org-service:
    build: .
    container_name: set_data_org_service
    command: python set_data.py
    environment:
      DATABASE_URL: ${DATABASE_URL}
    networks:
      - app-network
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: